### ISSUE TITLE
コードレビュー

### ISSUE THREAD

**Issue by laco0416** [Atoze/HTTP_Server#20]
## Server.java

- `HOST_NAME` 使われてない
- `request2` ?
- せっかくHTTPHandlerクラスを作っているのにポリモーフィズムの恩恵が受けられていない
- Handlerに対する処理が多い気がする 

```java
            if (filePath.startsWith("/program/board/")) {
                ForumAppHandler forum = new ForumAppHandler();
                forum.setRequest(httpRequest);
                forum.handle(httpRequest.getMethod());
                forum.response(output);

            } else {
                StaticHandler request2 = new StaticHandler();
                //StaticHandler request2 = new StaticHandler(httpRequest.getFilePath(), HOST_NAME + ":" + PORT);
                request2.setRequest(httpRequest);
                request2.response(output);
            }
```
は本質的には次の形にまとめられるはず

```java
            HTTPHandler handler;
            if (filePath.startsWith("/program/board/")) {
                handler = new ForumAppHandler(httpRequest);
            } else {
                handler = new StaticHandler(httpRequest);
            }
            handler.handle(output);
```

なぜならHandlerのインスタンスにとってHTTPRequestは一度与えられたら変更されない初期値だし、レスポンスは初期値として与えられたHTTPRequestのみによって影響されるから、Serverから必要な呼び出しはコンストラクタとメソッド1つだけで済むはず

## HTTPHandler.java

- `generateResponse()` が `HTTPResponse` を返すほうがスッキリしそう フィールドに持つ必要はないはず
- statusCodeも、HTTPResponseがStatusCodeを持てば解決する ステータスコードもレスポンスの一部

## HTTPResponse.java

- BodyFileとBodyTextが両方setされたとき両方writeされちゃう
- `response.getResponse()`というのはなんか変なので、 `toString()` とかでいいんじゃなかろうか

## CSVFile.java

- `readLine`のところ、 `\r\n` で引っ掛けたあとにそれぞれ単品で引っ掛ければいいんじゃなかろうか？

## ForumAppHandler.java

- `getHandler` だとHandlerをgetしてるので、書くなら `handleGET` 
- `forum.GETThread();` が名前から何が起きるのかの想像がまったくつかない

## ForumApp.java

- `newThread` は `createThread` 的な 動詞形に
- `GETThread` はなんか変

## ForumHTML.java

- `convertSanitize` は `sanitizeHTML` でよい

**Comment by Atoze** [comment]
Server.java
- [ ] HOST_NAMEを使用する
- [ ] HTTPHandlerクラスを作っているのにポリモーフィズムの恩恵が受けられていない
- [ ] Handlerに対する処理が多い気がする

HTTPHandler.java
- [ ] generateResponse() が HTTPResponse を返すほうがスッキリ
- [ ] statusCodeも、HTTPResponseがStatusCodeを持てば解決する

HTTPResponse.java
- [ ] BodyFileとBodyTextが両方setされたとき両方writeされる問題
- [ ] response.getResponse()を toString() に

**Comment by Atoze** [comment]
**CSVFile.java**
- [ ] readLineの修正

**ForumAppHandler.java**
- [ ] getHandlerだとHandlerをgetしてるので、書くなら handleGET
- [ ] forum.GETThread()が謎

**ForumApp.java**
- [ ] newThreadは createThread 的な 動詞形に
- [ ] GETThreadはなんか変

**ForumHTML.java**
- [ ] convertSanitizeは sanitizeHTML でよい

**Comment by laco0416** [comment]
## Server.java

- `handler.response(output);` は `response`が動詞じゃないのでよくない。`respond`とか `writeResponse`とかにしましょう

## HTTPHandler.java

- この抽象クラスにコンストラクタ要ります？

## HTTPRequest.java

- readLineのところ、 \r\n で引っ掛けたあとにそれぞれ単品で引っ掛ければいいんじゃなかろうか？
- HTTPRequestLineとHTTPRequestBodyが、似たような仕事をするのにメソッド名や使い方などのインターフェースが不揃いなのが気になる また、HTTPRequestはリクエストの状態を保持するのが仕事なのかと思いきやreadLineなどパース処理も一部請け負っている これらは何のためにHTTPRequestとクラスが分かれている？

## HTTPResponse.java

- bodyTextとbodyFileが排他にはなったけど、コードがいまいち読みづらいので、単純に if-else if文にしたほうがいいとおもう。どちらを優先するかはサーバーの仕様なので自由に決めていい

## ServerTest.java

- assertがないけど何をテストしている？例外が発生しないかどうか？テストケースの目的を書こう

## HTTPRequestTest.java

- サンプルファイルから読み出してテストするのはいいけど、テストのときにファイルを生成してそれを読み出す意味はないかなと思う。複数サンプルファイルを用意するほうが楽では？
- `間違ったリクエストがきた場合` のテストでwriterを使いまわしているけど、こういうのはそれぞれの異常系についてテストケースを分けましょう
- 同じファイルの中身を消したり書き込んだりしてたくさんのテストをするくらいなら、たくさんのファイルを用意するか、ファイルじゃなくてメモリ上に文字列からInputStreamを作ってテストするほうがよいです

---

ForumApp周りのテストがないな

**Comment by Atoze** [comment]
**Server.java**
- [ ] handler.response(output);を動詞にする
**HTTPHandler.java**
- [ ] コンストラクタ削除
**HTTPRequest.java**
- [ ] readLine修正
- [ ] HTTPRequestLineとHTTPRequestBodyのインターフェースが不揃い
- [ ] HTTPRequestはリクエストの状態を保持するのが仕事なのかと思いきやreadLineなどパース処理も一部請け負っている これらは何のためにHTTPRequestとクラスが分かれている？
**HTTPResponse.java**
- [ ] bodyTextとbodyFileが見辛いので単純に if-else if文にする

**Comment by Atoze** [comment]
**ServerTest.java**
- [ ] 謎テスト　テストケースの目的を書く

**HTTPRequestTest.java**
- [ ] サンプルファイルから読み出してテストするのはいいけど、テストのときにファイルを生成してそれを読み出す意味はないかなと思う。複数サンプルファイルを用意するほうが楽では？
- [ ] それぞれの異常系についてテストケースを分ける
- [ ] ファイルじゃなくてメモリ上に文字列からInputStreamを作ってテストする

- [ ] ForumApp周りのテスト作成

**Comment by Atoze** [comment]
readLineは仕様上 '\r' のみへの対応が厳しいので、HTTPRequestの前提である '\r\n' だけをとりあえず考えておくことにする。

**Comment by laco0416** [comment]
## HTTPRequestParser.java

- `String requestBodyBodyText = body.getBodyText();` 

だいたいよいのでは？
CSVFile.javaはForumApp限定のものなのか、utilなのかが微妙なところ。テストコードとメインのコードで階層構造が違っているのがよくない
