### ISSUE TITLE
ホワイトボックステスト 2

### ISSUE THREAD

**Issue by laco0416** [Atoze/HTTP_Server#28]
- 検索が半角英数にしか対応していないように見える

"寿司"を含むメッセージを"寿司"で検索できない

- formのbuttonに`name`が付けられているから送信されるform dataにbuttonのデータも載ってる 不要では

- 削除用のパスワード入力欄がtype=passwordじゃない

**Comment by laco0416** [comment]
- http://localhost:8080/ でgif画像がimage/mp4で配信されてるのは正しいんですっけ？

- resourceファイル

```
./src/main/resources/
├── 404.html
├── css
│   ├── board.css
│   └── top.css
├── img
│   ├── bird.png
│   ├── flower.jpg
│   ├── loading.gif
│   ├── save.csv  <--- この子はimg？
│   └── user.csv <--- 同上
```

**Comment by Atoze** [comment]
**app.forum.ForumHandler〜ForumData**
[ ] 日本語（マルチバイト）検索対応

**app.forum.ForumHTML**
[ ]  buttonの謎name
[ ]  パスワード入力欄を`type=password`に

**util.ContentType**
[ ] MIME-Typeの修正
[ ] ファイルの場所
