### ISSUE TITLE
課題2 コードレビュー by vv

### ISSUE THREAD

**Issue by vvakame** [Atoze/HTTP_Server#34]
* HTTPRequestLine#getFilePath が怪しい
  * 仕様的にはRequest URIであってFilePathではない…
  * 実際に /program/board/search?search=hoge で得られる結果はファイルではない
  * 仕様に対する準拠度の話(仕様と違うと混乱を生ずる可能性がある
  * getHeaderQuery も同様におかしいような気がしなくもない(query parameterと一般に呼んでいるものかと思う
* パスワードについて
  * 平文で保存されてていやーんな感じ
  * 文字数制限が短すぎるのもあまりよくない
    * わかめさんが普段使ってるパスワードジェネレータはデフォルトでは24桁のランダムな文字列を生成します
* URLPatternがenumな件について
  * Configurableであるべき項目についてenum(後から拡張できない)を使って管理するのは自由度が低いのであまりよくないと思う
  * 第三者がこのWebサーバを使う場合、プログラムに変更をくわえずに自分のアプリを乗っけるとしたらどういう構造になるだろうか…？
    * ↑これは実装内容としては結構難しいけど考えてみると面白い
* Server#checkValidRequest
  * if文の { } 抜きの書き方はやめたほうがいいと思います
  * 基本常に { } を使ったほうがよい(バグ防止のため
* Server#run
  * `if (response == null) { throw new Exception(); }` 的なやつ、乱暴では…
    * Internal Server Errorとか返すのが妥当そう
  * そして例外をcatchせずにthrowしているけどThreadだから親には伝播しないんだっけ…？ 親すら殺したい時はないのかな…？
* 200 とか 404 とかMagicNumberが多いかなー
  * 何番が何だったか稀に忘れるので定数とかにしておきたさがありますね
  * わかめさんはBad Requestが400だったか403だったかを毎回間違えます
* StaticHandler#generateResponse
  * 雑なことを言うと .htm という拡張子の使われ方もあります
  * `Arrays.asList("html", "txt")` は定数化し名前をつけておくべきかも
* HTTPResponse#writeTo
  * IOExceptionで `throw new RuntimeException(e);` するのはちょっと乱暴な気がする
  * FileNotFoundExceptionがタイミング的に発生する可能性がある
    * 200と判定した時点ではファイルあった→読もうとした瞬間にはなくなってた
* `jp.co.topgate.atoze.web.htmlEditor` package
  * 命名規則にあってないし含まれてるクラス名見てもなんかミスの香りがしてくる
* HTMLBuilder#setAttribute
  * boolean clear があまりよくない
  * setAttribute は上書き、appendAttribute は追加 みたいなのがJavaだと一般的だと思う
* 書き方が不揃い
  * `for (int i = 0; i < data.size(); i++) {` ってやってるとこあったり forEach使ってるとこあったりして不揃い…
  * なるべく書き方は統一しましょう
    * 読む人の脳にかかる負荷の問題 同じような構造の場合は同じような書き方をされているべき(逆もしかり
* 全体的に
  * String[] とか List<String> が多いような気がしなくもない
  * Stringは文字列であるということであり、その中身にどういうフォーマットの文字列を持つかということが表現できない
  * ので、できればもうちょっと型として制約をかけやすい別の形式で持ったほうがいいかなーという気持ち
* Server.javaにクラスが2つはいってるのよくない

総評：全体の構成はわりと良さそう。稀に読みにくいパート(HTMLBuilderとか)があるけどあまり大きな問題ではない…と思う。

**Comment by Atoze** [comment]
**HTTPRequestLine**
- [ ] getFilePath ではなくRequest URI
- [ ] getHeaderQuery ではなく一般的にはquery parameter

**Comment by Atoze** [comment]
**URLPattern**
- [ ] Configurableであるべき項目についてenumを使うのはあまりよくない
- [ ] 第三者がこのWebサーバを使う場合、プログラムに変更をくわえずに自分のアプリを乗っけるとしたらどういう構造になるだろうか

**Comment by Atoze** [comment]
**jp.co.topgate.atoze.web.htmlEditor package**
- [ ] 命名規則にあってない

**HTMLBuilder**
- [ ] boolean clear がよくない
setAttribute は上書き、appendAttribute は追加 みたいなのがJavaだと一般的だと思う

**Comment by Atoze** [comment]
**Forum系**
- [ ] 暗号化しよう
- [ ] 文字数制限をもうちょっと長く

**Comment by Atoze** [comment]
**全体的に散らばってる問題**
- [ ] if文の{ } 抜きの書き方はやめたほうがいい
- [ ] ステータスコード周りのMagicNumberを解消する
- [ ] `for (int i = 0; i < data.size(); i++) {` と`forEach`をどちらかに統合

- [ ] String[] とか List が多い、もうちょっと型として制約をかけやすい別の形式で持ったほうが良い

**Comment by Atoze** [comment]
**時間ができたら実装する：**
第三者がこのWebサーバを使う場合、プログラムに変更をくわえずに自分のアプリを乗っけるとしたらどういう構造になるだろうか
