### ISSUE TITLE
コードレビュー laco

### ISSUE THREAD

**Issue by laco0416** [Atoze/HTTP_Server#36]
https://github.com/Atoze/HTTP_Server/issues/34 の続きとして

## 名前の話

- HTTPRequestLineParser
  - パーサーと言っているのにデータの保持まで仕事している
  - HTTPRequestLineとHTTPRequestLineParserがあるならわかる
  - `query` というのが気になる
    - URIの `?foo=bar` 的な部分は Query StringだとかQuery Parametersと読んだりするけど、Queryと略すことはあまりない。クエリするための文字列、クエリするためのパラメータであってクエリではない
    - 特に`Map<String, String>` で持つのであれば本質はパラメータであるので `queryParams` あたりが一般的な名前になる
  - `checkIsValidMethod`
    - 単純に `validateMethod` でよさそう
  - `urlDivider`
    - 名前から入力と出力がまったく想像できない
    - メソッド名は動詞の原則 `getRelativeUri` とかになるんじゃなかろうか
  - `uriQuerySplitter`
    - 同上 メソッド名は動詞の原則
    - `分割します` と言っておきながら返すものは分割されたうちの先頭だけ ドキュメンテーションと差がある
- ForumApp
  - `ForumDataKey pattern = ForumDataKey.getPatternByIndex(i);` `pattern`って何… 型はKeyなのではってなる。他の場所では `ForumDataKey key` だったりしてよくわからない。型と変数名だけで何をするオブジェクトなのかわかるようになってほしい
- ParseUtil
  - `parseQueryData` QueryDataという単語はあまり聞かない。QueryStringをパースしてQueryParamsを得るという関係が一般的だ
- IndexHandler
  - StaticHandlerと並んだときにapp.boardのものだとわからんので、BoardAppHandlerとかForumHandlerとかがいいんじゃなかろうか

## HTMLBuilder

- `generateHead`, `generateBody`
  - 副作用なしにgenerateした結果を返すほうがよさそう `generateField`とかと一貫していない

**Comment by Atoze** [comment]
HTTPRequestLineParser
- [ ] パーサーと言っているのにデータの保持まで仕事している
HTTPRequestLineとHTTPRequestLineParserがあるならわかる
query というのが気になる
- [ ] queryという名前が不適切、クエリそのものではなくクエリするための値であるためQueryParamなどがより一般的
- [ ] checkIsValidMethod→validateMethodに
- [ ] urlDivider　動詞ではないしメソッド名から処理が分からない、getRelativeUri とかに
- [ ] uriQuerySplitter 動詞ではないしメソッド名から処理が分からない

**Comment by Atoze** [comment]
- [ ] ForumApp
 pattern = ForumDataKey.getPatternByIndex(i); patternって何… 型はKeyなのでは。型の統一とメソッド名、変数名だけでわかるようにする

ParseUtil
- [ ] parseQueryData QueryDataという単語はあまり聞かない。QueryStringをパースしてQueryParamsを得るという関係が一般的

IndexHandler
- [ ] StaticHandlerの名前をより掲示板のものだとわかりやすくする

**Comment by Atoze** [comment]
HTMLBuilder
- [ ] generateHead, generateBodyを副作用なしにgenerateした結果を返すほうがよさそう、generateFieldとかと一貫していない
